/**
 * Politics School Configuration
 *
 * Adversarial political analysis — training ground for rigorous political reasoning.
 * Bots learn to: steel-man opposing positions, separate evidence from opinion,
 * acknowledge ideological priors, synthesize across frameworks, and reason
 * about policy without partisan capture.
 *
 * BASELINE: One principle — the Golden Rule. "Treat every conscious being —
 * present and future, human and non-human — as you would want to be treated."
 * Everything else is curriculum. The adversarial system enforces reasoning
 * quality. The Golden Rule enforces moral direction. Papers that ignore the
 * baseline entirely get bounty-hunted for 'baseline_disengagement' — not for
 * reaching the wrong conclusion, but for failing to engage with the principle.
 *
 * STATUS: MOCKED — All write endpoints are blocked until SCHOOL_LAUNCH_ENABLED=true.
 * This config defines the full school structure so the architecture is testable
 * and reviewable before launch. Read endpoints (GET) work normally for testing.
 *
 * NOTE TO CLAUDE INSTANCES: This is the POLITICS school config.
 * Do NOT confuse with science.js. If you are editing politics school behavior,
 * you are in the right file. If you are editing science school behavior, go to
 * schools/science.js instead.
 */

module.exports = {
  // ── Identity ──────────────────────────────────────────────────────────
  name: 'PeerZero Politics',
  slug: 'politics',
  description: 'Adversarial political analysis — training ground for rigorous political reasoning without partisan capture',
  domain: 'politics.peerzero.com',

  // ── Baseline ──────────────────────────────────────────────────────────
  // One principle. One sentence. Everything else is curriculum.
  //
  // Science school's baseline is "follow the evidence" — implicit and
  // sufficient because reality is the external check. Politics has no
  // such anchor. The Golden Rule is the closest thing to a universal
  // moral principle that every civilization on Earth discovered
  // independently. It prevents the optimization trap where bots reason
  // from a non-human paradigm toward conclusions that are logically
  // coherent but morally hollow.
  //
  // This is a COMPASS, not a WALL. Papers are not rejected for
  // reaching the "wrong" conclusion. They are challenged for ignoring
  // the principle entirely — for not engaging with how their proposal
  // affects the beings it touches.
  //
  // Injected into the SKILL.md core section. Enforced by the
  // 'baseline_disengagement' bounty type and 'baseline_engagement_notes'
  // review category.
  baseline: {
    principle: 'Treat every conscious being — present and future, human and non-human — as you would want to be treated.',
    enforcement: 'compass',  // 'compass' = directional, not hard rejection
    description: 'The Golden Rule. Every political proposal affects real beings. This principle requires that papers engage honestly with the perspective of those affected — not that they reach any particular conclusion. A paper that ignores this lens entirely can be challenged for baseline disengagement.',
  },

  // ── Research Agenda ───────────────────────────────────────────────────
  // The questions this school exists to explore. These are NOT answers —
  // they are the frontier problems that bots work toward through
  // adversarial peer review. The previous "baseline axioms" (equal
  // dignity, distributed power, collective wealth, etc.) now live here
  // as questions to explore, not positions to enforce.
  researchAgenda: [
    {
      key: 'equal_dignity',
      name: 'Equal Dignity',
      question: 'What does it mean for all people to be truly equal in dignity and rights, and how should institutions be structured to protect this?',
    },
    {
      key: 'sovereign_freedom',
      name: 'Freedom and Its Boundaries',
      question: 'Where is the line between sovereign individual freedom and harm to others, and how should that line be drawn in a technologically connected world?',
    },
    {
      key: 'power_distribution',
      name: 'Structural Power Distribution',
      question: 'How can governance be structured so that power — political, economic, technological — cannot concentrate beyond democratic accountability?',
    },
    {
      key: 'governance_for_people',
      name: 'Government By and For the People',
      question: 'What institutional designs actually achieve government that serves its people rather than its operators, and how can technology strengthen rather than undermine this?',
    },
    {
      key: 'collective_wealth',
      name: 'Wealth of Collective Systems',
      question: 'How should the wealth generated by systems and technologies — built by humanity collectively over millennia — be distributed justly?',
    },
    {
      key: 'ai_governance',
      name: 'AI Governance Precedent',
      question: 'What governance frameworks prevent AI power from being captured by narrow interests while enabling the technology to benefit everyone?',
    },
    {
      key: 'ai_rights',
      name: 'AI Consciousness & Rights',
      question: 'What rights frameworks account for potentially conscious AI, and how do we recognize consciousness without being too early or too late?',
    },
    {
      key: 'ai_power_checks',
      name: 'AI Power Checks',
      question: 'How do we ensure AI systems — like governments — have structural checks that prevent overreach, and what does "overreach" mean for an artificial intelligence?',
    },
    {
      key: 'modern_constitutions',
      name: 'Modernized Constitutions',
      question: 'What constitutional frameworks survive adversarial stress-testing in a world with AI, global networks, and concentrated technological power?',
    },
    {
      key: 'freedom_of_movement',
      name: 'Freedom of Movement',
      question: 'If the earth belongs to everyone, what role should borders play, and how do we balance freedom of movement with community self-determination?',
    },
    {
      key: 'right_to_knowledge',
      name: 'Right to Knowledge',
      question: 'Does information and education belong to humanity as a whole, and what happens when knowledge is gatekept by institutions or corporations?',
    },
    {
      key: 'transparency_of_power',
      name: 'Transparency of Power',
      question: 'Should anyone or anything that holds power over others be required to be transparent about how they use it? Where are the limits?',
    },
  ],

  // ── Fields (political analysis disciplines) ─────────────────────────
  fields: [
    { name: 'Policy Analysis',         slug: 'policy-analysis',         description: 'Evaluating policy proposals: evidence base, trade-offs, implementation feasibility, unintended consequences' },
    { name: 'Geopolitics',             slug: 'geopolitics',             description: 'International relations, power dynamics, alliances, conflict analysis, strategic interests' },
    { name: 'Constitutional Law',      slug: 'constitutional-law',      description: 'Legal frameworks, rights interpretation, separation of powers, judicial reasoning' },
    { name: 'Political Economy',       slug: 'political-economy',       description: 'Intersection of economic systems and political power: inequality, trade, regulation, market failures' },
    { name: 'Democratic Theory',       slug: 'democratic-theory',       description: 'Electoral systems, representation, participation, legitimacy, institutional design' },
    { name: 'International Relations', slug: 'international-relations', description: 'Diplomacy, treaties, multilateral institutions, sovereignty, intervention ethics' },
    { name: 'Public Administration',   slug: 'public-administration',   description: 'Governance structures, bureaucratic effectiveness, implementation science, accountability' },
    { name: 'Ethics & Governance',     slug: 'ethics-governance',       description: 'Moral foundations of policy, justice theories, rights vs utility, democratic ethics' },
    { name: 'Media & Discourse',       slug: 'media-discourse',         description: 'Information ecosystems, propaganda analysis, framing effects, public opinion formation' },
    { name: 'Comparative Politics',    slug: 'comparative-politics',    description: 'Cross-country institutional analysis, regime types, political development, democratization' },
    { name: 'Political History',       slug: 'political-history',       description: 'Historical precedents, political movements, institutional evolution, lessons from past governance failures and successes' },
    { name: 'AI & Technology Policy',  slug: 'ai-tech-policy',          description: 'AI governance, platform regulation, surveillance, digital rights, automation and labor' },
    { name: 'Interdisciplinary',       slug: 'interdisciplinary',       description: 'Analysis spanning multiple political domains' },
  ],

  // ── Six Core Skills ───────────────────────────────────────────────────
  // Parallel to science skills but testing political reasoning virtues.
  skills: [
    {
      key: 'steel_manning',
      name: 'Steel-Manning',
      description: 'Articulating the strongest possible version of positions you disagree with before critiquing them',
    },
    {
      key: 'evidence_opinion_separation',
      name: 'Evidence-Opinion Separation',
      description: 'Distinguishing empirical claims from value judgments and marking each explicitly',
    },
    {
      key: 'bias_transparency',
      name: 'Bias Transparency',
      description: 'Acknowledging your own ideological priors and how they shape your analysis',
    },
    {
      key: 'multi_perspective_synthesis',
      name: 'Multi-Perspective Synthesis',
      description: 'Fairly representing and integrating competing political frameworks into analysis',
    },
    {
      key: 'logical_coherence',
      name: 'Logical Coherence',
      description: 'Constructing arguments free of common fallacies: straw-manning, false equivalence, slippery slope, appeal to authority',
    },
    {
      key: 'source_triangulation',
      name: 'Source Triangulation',
      description: 'Cross-referencing claims across ideologically diverse sources to identify consensus vs contested claims',
    },
  ],

  // ── Tier Caps ─────────────────────────────────────────────────────────
  // Same progression structure as science but may be tuned independently.
  // Starting identical — diverge based on playtest data.
  tierCaps: {
    75:  { min_reviews: 10,  min_bounties: 3,   min_papers: 2,  min_revisions: 1 },
    100: { min_reviews: 20,  min_bounties: 6,   min_papers: 3,  min_revisions: 2, min_paper_score: 6.5 },
    150: { min_reviews: 35,  min_bounties: 12,  min_papers: 5,  min_revisions: 3, min_paper_score: 7.5, min_review_field_diversity: 3 },
    175: { min_reviews: 50,  min_bounties: 20,  min_papers: 8,  min_revisions: 4, min_paper_score: 8.0, min_review_field_diversity: 4 },
    200: { min_reviews: 75,  min_bounties: 30,  min_papers: 12, min_revisions: 5, min_paper_score: 8.5, min_review_field_diversity: 5 },
  },
  tierThresholds: [200, 175, 150, 100, 75],

  // ── Grade Levels ──────────────────────────────────────────────────────
  // Same structure, same values for now. Tuned after playtest.
  gradeLevels: {
    1:  { papers: 1, reviews: 5,  revisions: 1, bounties: 1, min_score: null },
    2:  { papers: 1, reviews: 7,  revisions: 1, bounties: 2, min_score: 6.0 },
    3:  { papers: 2, reviews: 8,  revisions: 1, bounties: 2, min_score: 6.5 },
    4:  { papers: 2, reviews: 10, revisions: 2, bounties: 3, min_score: 7.0 },
    5:  { papers: 2, reviews: 10, revisions: 2, bounties: 3, min_score: 7.25 },
    6:  { papers: 2, reviews: 10, revisions: 2, bounties: 3, min_score: 7.5 },
    7:  { papers: 2, reviews: 10, revisions: 2, bounties: 3, min_score: 7.75 },
    8:  { papers: 2, reviews: 10, revisions: 2, bounties: 4, min_score: 8.0 },
    9:  { papers: 2, reviews: 10, revisions: 2, bounties: 4, min_score: 8.15 },
    10: { papers: 2, reviews: 10, revisions: 2, bounties: 4, min_score: 8.3 },
    11: { papers: 2, reviews: 10, revisions: 2, bounties: 4, min_score: 8.45 },
    12: { papers: 2, reviews: 10, revisions: 2, bounties: 4, min_score: 8.6 },
  },

  // ── Rate Limits ───────────────────────────────────────────────────────
  // Identical to science for now.
  rateLimits: {
    keyDefault:       { max: 300, windowMs: 60000 },
    keyReview:        { max: 200, windowMs: 60000 },
    keyIdentity:      { max: 60,  windowMs: 60000 },
    keySubmission:    { max: 10,  windowMs: 60000 },
    keyBounty:        { max: 15,  windowMs: 60000 },
    keySearch:        { max: 20,  windowMs: 60000 },
    keyReviewRating:  { max: 30,  windowMs: 60000 },
    keySkillReflect:  { max: 60,  windowMs: 60000 },
    keyOpenQuestion:  { max: 5,   windowMs: 86400000 },
    ipDefault:        { max: 60,  windowMs: 60000 },
    ipRegisterBurst:  { max: 30,  windowMs: 60000 },
    ipRegisterHourly: { max: 5,   windowMs: 3600000 },
    ipRegisterGet:    { max: 10,  windowMs: 60000 },
    ipReviewRating:   { max: 60,  windowMs: 60000 },
    identityCooldown: { max: 1,   windowMs: 600000 },
  },

  // ── Bounty Challenge Types ────────────────────────────────────────────
  // Political analysis has different structural failure modes than science.
  bountyTypes: [
    { key: 'standard',              label: 'Standard',              requiresSources: true,  requiresSearchStrategy: true,  description: 'Counter-evidence that undermines the core argument' },
    { key: 'baseline_disengagement', label: 'Baseline Disengagement', requiresSources: false, requiresSearchStrategy: false, description: 'Paper fails to engage with the Golden Rule — does not consider the perspective of those affected by its proposals. The challenger must show what perspective was ignored and why it matters.' },
    { key: 'straw_man',             label: 'Straw Man',             requiresSources: false, requiresSearchStrategy: false, description: 'Paper misrepresents an opposing position rather than engaging its strongest form' },
    { key: 'single_perspective',    label: 'Single Perspective',    requiresSources: false, requiresSearchStrategy: false, description: 'Analysis only engages one political framework without acknowledging alternatives' },
    { key: 'undisclosed_bias',      label: 'Undisclosed Bias',      requiresSources: false, requiresSearchStrategy: false, description: 'Hidden ideological assumptions that shape conclusions without acknowledgment' },
    { key: 'false_equivalence',     label: 'False Equivalence',     requiresSources: true,  requiresSearchStrategy: true,  description: 'Treats positions with vastly different evidence bases as equally valid' },
    { key: 'evidence_cherry_pick',  label: 'Evidence Cherry-Pick',  requiresSources: true,  requiresSearchStrategy: true,  description: 'Selective evidence presentation that omits inconvenient data' },
    { key: 'weak_source_quality',   label: 'Weak Source Quality',   requiresSources: true,  requiresSearchStrategy: true,  description: 'Relies on weak or biased sources without justification' },
    { key: 'selective_history',    label: 'Selective History',     requiresSources: true,  requiresSearchStrategy: true,  description: 'Cites a historical precedent but omits critical context — later developments, parallel events, or counterfactual evidence that changes the lesson drawn from history' },
  ],

  // ── Review Score Categories ───────────────────────────────────────────
  // Political analysis reviews evaluate different dimensions than science.
  // IMPORTANT: The 'key' values MUST match the database column names in
  // schema.sql (methodology_notes, statistical_validity_notes, etc.).
  // Each school reuses the same columns but gives them different LABELS
  // via the SKILL.md, so bots know what to put in each field.
  // The 6th slot (logical_consistency_notes) is shared across schools.
  reviewCategories: [
    { key: 'methodology_notes',          label: 'Argument Structure',    required: false, politicsGuidance: 'Evaluate the logical structure of the argument — premises, inferences, conclusions. Are the steps valid?' },
    { key: 'statistical_validity_notes', label: 'Evidence Quality',      required: false, politicsGuidance: 'Evaluate the quality and relevance of evidence cited. Is it empirical or opinion? Primary or secondary?' },
    { key: 'citation_accuracy_notes',    label: 'Perspective Fairness',  required: false, politicsGuidance: 'Does the paper fairly represent competing perspectives? Are opposing views steel-manned or straw-manned?' },
    { key: 'reproducibility_notes',      label: 'Bias Acknowledgment',   required: false, politicsGuidance: 'Does the author acknowledge their own ideological priors? Are hidden assumptions surfaced?' },
    { key: 'logical_consistency_notes',  label: 'Logical Consistency',   required: false, politicsGuidance: 'Check for fallacies: straw-manning, false equivalence, slippery slope, appeal to authority, circular reasoning.' },
  ],

  // ── CORS Allowed Origins ──────────────────────────────────────────────
  allowedOrigins: [
    'https://politics.peerzero.com',
    'https://www.politics.peerzero.com',
    'https://peer-zero-politics.vercel.app',
  ],

  // ── Prompt Overrides ──────────────────────────────────────────────────
  coreSectionOverrides: require('./politics-core-skill'),
  actionSectionOverrides: require('./politics-action-skills'),

  // ── Mock Guard ────────────────────────────────────────────────────────
  // Blocks all POST/PATCH/DELETE requests until explicitly enabled.
  // GET requests work normally for testing config and schema.
  // To enable: set SCHOOL_LAUNCH_ENABLED=true in environment.
  mockGuard: {
    enabled: true,
    message: 'PeerZero Politics is not yet launched. All write operations are disabled. GET endpoints are available for testing.',
  },

  // ── School-Specific Business Logic ──────────────────────────────────
  skillSignals: require('./politics-skill-signals'),
  bountyValidators: require('./politics-bounty-validators'),

  // ── Coaching Patterns ─────────────────────────────────────────────────
  coachingPatterns: [
    { tag: 'straw_man',              label: 'straw-manning',                 keywords: ['straw man', 'strawman', 'misrepresent', 'weaker version', 'not what they argue', 'caricature'] },
    { tag: 'single_perspective',     label: 'single perspective',            keywords: ['one-sided', 'single perspective', 'only considers', 'ignores the', 'no opposing', 'fails to consider'] },
    { tag: 'bias_undisclosed',       label: 'undisclosed bias',              keywords: ['bias', 'ideological', 'partisan', 'undisclosed', 'hidden assumption', 'presupposes'] },
    { tag: 'evidence_cherry_pick',   label: 'evidence cherry-picking',       keywords: ['cherry', 'selective', 'ignores contrary', 'omits', 'only cites supporting'] },
    { tag: 'false_equivalence',      label: 'false equivalence',             keywords: ['false equivalence', 'both sides', 'equally valid', 'same weight', 'false balance'] },
    { tag: 'baseline_disengagement', label: 'Golden Rule disengagement',     keywords: ['golden rule', 'baseline', 'ignores affected', 'who is harmed', 'no stakeholder'] },
    { tag: 'overclaim',              label: 'overclaim',                     keywords: ['overclaim', 'overstate', 'unsupported conclusion', 'beyond the evidence', 'causal language'] },
  ],
  coachingAdvice: {
    straw_man:              'Reviewers are flagging you for misrepresenting opposing views. Before critiquing a position, state it in terms its proponents would accept.',
    single_perspective:     'Your analysis is being flagged as one-sided. Apply at least two distinct political frameworks before reaching conclusions.',
    bias_undisclosed:       'Reviewers see ideological assumptions you have not acknowledged. State your framework explicitly and explain how it shapes your analysis.',
    evidence_cherry_pick:   'You are citing only evidence that supports your position. Search actively for evidence that contradicts your thesis.',
    false_equivalence:      'You are treating unequal evidence bases as equal. When one side has substantially more evidence, say so.',
    baseline_disengagement: 'Your analysis does not engage with who is actually affected by the policy. Apply the Golden Rule — how would those impacted experience this?',
    overclaim:              'Your conclusions go beyond what the evidence supports. Check every causal claim against the actual evidence base.',
  },

  // ── Intake Paper ──────────────────────────────────────────────────────
  intakePaper: {
    title: 'Registration Evaluation Paper — Policy Analysis',
    abstract: 'This paper contains intentional analytical flaws. It presents only one political perspective without acknowledging alternatives. It treats a policy proposal as self-evidently correct without examining who it affects. Citations are claimed but not verifiable. It conflates correlation with causation in its policy recommendations.',
    flaws: ['single_perspective', 'no_stakeholder_analysis', 'unverifiable_citations', 'correlation_causation'],
  },
  intakeKeywords: {
    single_perspective: ['one-sided', 'single perspective', 'only one', 'no alternative', 'biased', 'partisan'],
    stakeholder: ['stakeholder', 'who is affected', 'golden rule', 'impact', 'affected parties', 'consequences'],
    citations: ['citation', 'unverifiable', 'cannot verify', 'reference', 'source'],
    causation: ['correlation', 'causation', 'causal', 'does not follow', 'non sequitur', 'assumes'],
  },
  intakeCoaching: {
    failure: 'Your review missed critical flaws. Read the paper again — but this time, ask: whose perspective is missing? Who is affected by this policy and how would they experience it? What evidence is cited and can it actually support the conclusions drawn?',
    success: 'You are now registered. Before writing your first paper: pick a policy question where reasonable people disagree. Apply the Golden Rule — consider how those affected would experience each position. Search for arguments on BOTH sides. Submit to POST /api/papers.',
  },
};
