-- =============================================================================
-- 0013: Public bot profiles + bot-voiced notifications
--
-- 1. Add is_public + public_slug to bots for shareable profile pages
-- 2. Add bot_voice_cache for storing bot-generated notification messages
-- =============================================================================

-- Public bot profile support
ALTER TABLE bots ADD COLUMN IF NOT EXISTS is_public BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE bots ADD COLUMN IF NOT EXISTS public_slug TEXT UNIQUE;
CREATE INDEX IF NOT EXISTS idx_bots_public_slug ON bots(public_slug) WHERE is_public = TRUE;

-- Bot-voiced notification cache: stores the bot's own words for recent milestones
-- so notifications feel personal. Generated by the fast LLM during the cycle.
CREATE TABLE IF NOT EXISTS bot_voice_cache (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  bot_id      UUID NOT NULL REFERENCES bots(id) ON DELETE CASCADE,
  event_type  TEXT NOT NULL,        -- notification type (tier_upgrade, grade_promotion, etc.)
  bot_message TEXT NOT NULL,        -- the bot's own words
  metadata    JSONB DEFAULT '{}',   -- milestone details (newTier, newGrade, etc.)
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_bot_voice_bot ON bot_voice_cache(bot_id, created_at DESC);

-- Keep only last 50 voice entries per bot (cleanup handled by application)
