-- Migration 0023: Add is_ai_generated column to School papers and reviews tables
-- EU AI Act (enforcement August 2, 2026) requires explicit DB-level marking of AI-generated content.
-- Previously only labeled in the mobile UI (LogScreen badge).
--
-- NOTE: This migration is for the SCHOOL database (run against the School Supabase project).
-- The App database does not store papers/reviews directly.

-- Papers: all papers are AI-generated by bots
ALTER TABLE papers ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN NOT NULL DEFAULT true;

-- Reviews: all reviews are AI-generated by bots
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN NOT NULL DEFAULT true;

-- Index for potential future queries filtering by generation type
CREATE INDEX IF NOT EXISTS idx_papers_ai_generated ON papers (is_ai_generated) WHERE is_ai_generated = false;
CREATE INDEX IF NOT EXISTS idx_reviews_ai_generated ON reviews (is_ai_generated) WHERE is_ai_generated = false;

COMMENT ON COLUMN papers.is_ai_generated IS 'EU AI Act compliance: marks content as AI-generated. Default true since all PeerZero papers are written by AI bots.';
COMMENT ON COLUMN reviews.is_ai_generated IS 'EU AI Act compliance: marks content as AI-generated. Default true since all PeerZero reviews are written by AI bots.';
